### ISSUE TITLE
Is there a way to specify key file when using SSH

### ISSUE THREAD

**Issue by DaveSpe** [lvrfrc87/git-acp-ansible#39]
I have a use case where I prefer to use ssh key over username and token.

Is there a way to specify ssh rsa file when using `mode: ssh` ?

**Comment by DaveSpe** [comment]
Nevermind if you use just the token the user name is not necessary.

**Comment by lvrfrc87** [comment]
Hi @DaveSpe,

If you load your ssh key in github/gitlab and you pass just the ssh url to the module - without username and password, you should be able to connect to git

**Comment by DaveSpe** [comment]
The above use case does not work for me. 
I use automation and would like to avoid using an ssh key loaded into a config file or using the system default rsa. 
I am fetching a specific key from Ansible Vault, which is generated just for this purpose.  
We have several users using the automation so we'd like to keep using the key without having to store it on every machine that this runs on. 

Also `ansible.builtin.git` supports `key_file`, was just curious if your collection supports something similar. 


Git supports something like this: 
`GIT_SSH_COMMAND='ssh -i ~/.ssh/github.rsa -o IdentitiesOnly=yes' git push ssh://git@github.com/MyOrg/repo.git`

I have tested the above and it works, for commits and other git commands. 
What about incorporating this into your collection?

**Comment by lvrfrc87** [comment]
Few considerations:

- `ansible.builtin.git` set-up `key_file` via env var which is out of scope for this module. You can consider this approach - https://github.com/ansible/ansible/blob/23414869e2d4ab313212528ecf0f2ef8f0a570e1/lib/ansible/modules/git.py#L465

- `git config` is handled by git config module so you might want to consider that as prior task to `git_acp`- https://docs.ansible.com/ansible/latest/collections/community/general/git_config_module.html

One of the challenges when such type of modules are developed is to keep a clear demarcation point of what is module competence and what is not: adding features might hand up in a supercool swiss knife module that however might grow exponentially and become hard to  maintain as well as overlapping with other modules. 

I made an exception in `git_acp` with `user.name` and `user.password` only because they are required during `git commit` and `git` would throw an error otherwise.

As rule of thumb, I say that: "Whatever is strictly related to `git add`, `git commit` and `git push` operations will fell under `git_acp` competence, all the rest must be handled by other modules.

Hope it make sense :)

Federico

**Comment by DaveSpe** [comment]
Thanks  for the clear up and the write up. 
I appreciate it. 

Dave
